// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(LandContext))]
    [Migration("20250928125521_SeedPriority1to3Lands")]
    partial class SeedPriority1to3Lands
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Domain.Models.DataModels.LandData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Colors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Lands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Colors = "[\"white\",\"blue\"]",
                            Name = "Tundra",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Colors = "[\"blue\",\"black\"]",
                            Name = "Underground Sea",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Colors = "[\"black\",\"red\"]",
                            Name = "Badlands",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Colors = "[\"red\",\"green\"]",
                            Name = "Taiga",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Colors = "[\"green\",\"white\"]",
                            Name = "Savannah",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Colors = "[\"white\",\"black\"]",
                            Name = "Scrubland",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 7,
                            Colors = "[\"blue\",\"red\"]",
                            Name = "Volcanic Island",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            Colors = "[\"green\",\"blue\"]",
                            Name = "Tropical Island",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 9,
                            Colors = "[\"black\",\"green\"]",
                            Name = "Bayou",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            Colors = "[\"red\",\"white\"]",
                            Name = "Plateau",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 11,
                            Colors = "[\"white\",\"blue\"]",
                            Name = "Flooded Strand",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 12,
                            Colors = "[\"blue\",\"black\"]",
                            Name = "Polluted Delta",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 13,
                            Colors = "[\"black\",\"red\"]",
                            Name = "Bloodstained Mire",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 14,
                            Colors = "[\"red\",\"green\"]",
                            Name = "Wooded Foothills",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 15,
                            Colors = "[\"green\",\"white\"]",
                            Name = "Windswept Heath",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 16,
                            Colors = "[\"white\",\"black\"]",
                            Name = "Marsh Flats",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 17,
                            Colors = "[\"blue\",\"red\"]",
                            Name = "Scalding Tarn",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 18,
                            Colors = "[\"green\",\"blue\"]",
                            Name = "Misty Rainforest",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 19,
                            Colors = "[\"black\",\"green\"]",
                            Name = "Verdant Catacombs",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 20,
                            Colors = "[\"red\",\"white\"]",
                            Name = "Arid Mesa",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 21,
                            Colors = "[\"white\",\"blue\"]",
                            Name = "Hallowed Fountain",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 22,
                            Colors = "[\"blue\",\"black\"]",
                            Name = "Watery Grave",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 23,
                            Colors = "[\"black\",\"red\"]",
                            Name = "Blood Crypt",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 24,
                            Colors = "[\"red\",\"green\"]",
                            Name = "Stomping Ground",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 25,
                            Colors = "[\"green\",\"white\"]",
                            Name = "Temple Garden",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 26,
                            Colors = "[\"white\",\"black\"]",
                            Name = "Godless Shrine",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 27,
                            Colors = "[\"blue\",\"red\"]",
                            Name = "Steam Vents",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 28,
                            Colors = "[\"green\",\"blue\"]",
                            Name = "Breeding Pool",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 29,
                            Colors = "[\"black\",\"green\"]",
                            Name = "Overgrown Tomb",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 30,
                            Colors = "[\"red\",\"white\"]",
                            Name = "Sacred Foundry",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 31,
                            Colors = "[\"white\",\"blue\"]",
                            Name = "Sea of Clouds",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 32,
                            Colors = "[\"blue\",\"black\"]",
                            Name = "Morphic Pool",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 33,
                            Colors = "[\"black\",\"red\"]",
                            Name = "Luxury Suite",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 34,
                            Colors = "[\"red\",\"green\"]",
                            Name = "Spire Garden",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 35,
                            Colors = "[\"green\",\"white\"]",
                            Name = "Bountiful Promenade",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 36,
                            Colors = "[\"white\",\"black\"]",
                            Name = "Vault of Champions",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 37,
                            Colors = "[\"blue\",\"red\"]",
                            Name = "Training Center",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 38,
                            Colors = "[\"black\",\"green\"]",
                            Name = "Undergrowth Stadium",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 39,
                            Colors = "[\"red\",\"white\"]",
                            Name = "Spectator Seating",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 40,
                            Colors = "[\"green\",\"blue\"]",
                            Name = "Rejuvenating Spring",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 41,
                            Colors = "[\"white\",\"blue\",\"red\"]",
                            Name = "Raugrin Triome",
                            TypeId = 5
                        },
                        new
                        {
                            Id = 42,
                            Colors = "[\"white\",\"black\",\"green\"]",
                            Name = "Indatha Triome",
                            TypeId = 5
                        },
                        new
                        {
                            Id = 43,
                            Colors = "[\"blue\",\"red\",\"green\"]",
                            Name = "Ketria Triome",
                            TypeId = 5
                        },
                        new
                        {
                            Id = 44,
                            Colors = "[\"red\",\"white\",\"black\"]",
                            Name = "Savai Triome",
                            TypeId = 5
                        },
                        new
                        {
                            Id = 45,
                            Colors = "[\"black\",\"green\",\"blue\"]",
                            Name = "Zagoth Triome",
                            TypeId = 5
                        },
                        new
                        {
                            Id = 46,
                            Colors = "[\"red\",\"green\",\"white\"]",
                            Name = "Jetmir's Garden",
                            TypeId = 5
                        },
                        new
                        {
                            Id = 47,
                            Colors = "[\"green\",\"white\",\"blue\"]",
                            Name = "Spara's Headquarters",
                            TypeId = 5
                        },
                        new
                        {
                            Id = 48,
                            Colors = "[\"blue\",\"black\",\"red\"]",
                            Name = "Xander's Lounge",
                            TypeId = 5
                        },
                        new
                        {
                            Id = 49,
                            Colors = "[\"black\",\"red\",\"green\"]",
                            Name = "Ziatora's Proving Ground",
                            TypeId = 5
                        },
                        new
                        {
                            Id = 50,
                            Colors = "[\"white\",\"blue\",\"black\"]",
                            Name = "Raffine's Tower",
                            TypeId = 5
                        },
                        new
                        {
                            Id = 51,
                            Colors = "[\"white\",\"blue\"]",
                            Name = "Glacial Fortress",
                            TypeId = 6
                        },
                        new
                        {
                            Id = 52,
                            Colors = "[\"blue\",\"black\"]",
                            Name = "Drowned Catacomb",
                            TypeId = 6
                        },
                        new
                        {
                            Id = 53,
                            Colors = "[\"black\",\"red\"]",
                            Name = "Dragonskull Summit",
                            TypeId = 6
                        },
                        new
                        {
                            Id = 54,
                            Colors = "[\"red\",\"green\"]",
                            Name = "Rootbound Crag",
                            TypeId = 6
                        },
                        new
                        {
                            Id = 55,
                            Colors = "[\"green\",\"white\"]",
                            Name = "Sunpetal Grove",
                            TypeId = 6
                        },
                        new
                        {
                            Id = 56,
                            Colors = "[\"white\",\"black\"]",
                            Name = "Isolated Chapel",
                            TypeId = 6
                        },
                        new
                        {
                            Id = 57,
                            Colors = "[\"blue\",\"red\"]",
                            Name = "Sulfur Falls",
                            TypeId = 6
                        },
                        new
                        {
                            Id = 58,
                            Colors = "[\"green\",\"blue\"]",
                            Name = "Hinterland Harbor",
                            TypeId = 6
                        },
                        new
                        {
                            Id = 59,
                            Colors = "[\"black\",\"green\"]",
                            Name = "Woodland Cemetery",
                            TypeId = 6
                        },
                        new
                        {
                            Id = 60,
                            Colors = "[\"red\",\"white\"]",
                            Name = "Clifftop Retreat",
                            TypeId = 6
                        },
                        new
                        {
                            Id = 61,
                            Colors = "[\"white\",\"blue\"]",
                            Name = "Adarkar Wastes",
                            TypeId = 7
                        },
                        new
                        {
                            Id = 62,
                            Colors = "[\"blue\",\"black\"]",
                            Name = "Underground River",
                            TypeId = 7
                        },
                        new
                        {
                            Id = 63,
                            Colors = "[\"black\",\"red\"]",
                            Name = "Sulfurous Springs",
                            TypeId = 7
                        },
                        new
                        {
                            Id = 64,
                            Colors = "[\"red\",\"green\"]",
                            Name = "Karplusan Forest",
                            TypeId = 7
                        },
                        new
                        {
                            Id = 65,
                            Colors = "[\"green\",\"white\"]",
                            Name = "Brushland",
                            TypeId = 7
                        },
                        new
                        {
                            Id = 66,
                            Colors = "[\"white\",\"black\"]",
                            Name = "Caves of Koilos",
                            TypeId = 7
                        },
                        new
                        {
                            Id = 67,
                            Colors = "[\"blue\",\"red\"]",
                            Name = "Shivan Reef",
                            TypeId = 7
                        },
                        new
                        {
                            Id = 68,
                            Colors = "[\"black\",\"green\"]",
                            Name = "Llanowar Wastes",
                            TypeId = 7
                        },
                        new
                        {
                            Id = 69,
                            Colors = "[\"red\",\"white\"]",
                            Name = "Battlefield Forge",
                            TypeId = 7
                        },
                        new
                        {
                            Id = 70,
                            Colors = "[\"green\",\"blue\"]",
                            Name = "Yavimaya Coast",
                            TypeId = 7
                        },
                        new
                        {
                            Id = 71,
                            Colors = "[\"white\",\"blue\"]",
                            Name = "Seachrome Coast",
                            TypeId = 8
                        },
                        new
                        {
                            Id = 72,
                            Colors = "[\"blue\",\"black\"]",
                            Name = "Darkslick Shores",
                            TypeId = 8
                        },
                        new
                        {
                            Id = 73,
                            Colors = "[\"black\",\"red\"]",
                            Name = "Bloodfell Caves",
                            TypeId = 8
                        },
                        new
                        {
                            Id = 74,
                            Colors = "[\"red\",\"white\"]",
                            Name = "Inspiring Vantage",
                            TypeId = 8
                        },
                        new
                        {
                            Id = 75,
                            Colors = "[\"green\",\"blue\"]",
                            Name = "Botanical Sanctum",
                            TypeId = 8
                        },
                        new
                        {
                            Id = 76,
                            Colors = "[\"red\",\"green\"]",
                            Name = "Cinder Glade",
                            TypeId = 8
                        },
                        new
                        {
                            Id = 77,
                            Colors = "[\"white\",\"blue\"]",
                            Name = "Glacial Fortress",
                            TypeId = 8
                        },
                        new
                        {
                            Id = 78,
                            Colors = "[\"green\",\"blue\"]",
                            Name = "Hinterland Harbor",
                            TypeId = 8
                        },
                        new
                        {
                            Id = 79,
                            Colors = "[\"red\",\"white\"]",
                            Name = "Clifftop Retreat",
                            TypeId = 8
                        },
                        new
                        {
                            Id = 80,
                            Colors = "[\"black\",\"green\"]",
                            Name = "Woodland Cemetery",
                            TypeId = 8
                        },
                        new
                        {
                            Id = 81,
                            Colors = "[\"white\",\"blue\"]",
                            Name = "Hengegate Pathway",
                            TypeId = 9
                        },
                        new
                        {
                            Id = 82,
                            Colors = "[\"blue\",\"black\"]",
                            Name = "Clearwater Pathway",
                            TypeId = 9
                        },
                        new
                        {
                            Id = 83,
                            Colors = "[\"black\",\"red\"]",
                            Name = "Blightstep Pathway",
                            TypeId = 9
                        },
                        new
                        {
                            Id = 84,
                            Colors = "[\"red\",\"white\"]",
                            Name = "Boulderloft Pathway",
                            TypeId = 9
                        },
                        new
                        {
                            Id = 85,
                            Colors = "[\"green\",\"white\"]",
                            Name = "Branchloft Pathway",
                            TypeId = 9
                        },
                        new
                        {
                            Id = 86,
                            Colors = "[\"red\",\"green\"]",
                            Name = "Grimclimb Pathway",
                            TypeId = 9
                        },
                        new
                        {
                            Id = 87,
                            Colors = "[\"blue\",\"green\"]",
                            Name = "Riverglide Pathway",
                            TypeId = 9
                        },
                        new
                        {
                            Id = 88,
                            Colors = "[\"black\",\"white\"]",
                            Name = "Shambling Vent",
                            TypeId = 9
                        },
                        new
                        {
                            Id = 89,
                            Colors = "[\"black\",\"red\"]",
                            Name = "Sundown Pathway",
                            TypeId = 9
                        },
                        new
                        {
                            Id = 90,
                            Colors = "[\"white\",\"green\"]",
                            Name = "Brightclimb Pathway",
                            TypeId = 9
                        },
                        new
                        {
                            Id = 91,
                            Colors = "[\"white\",\"blue\"]",
                            Name = "Deserted Beach",
                            TypeId = 10
                        },
                        new
                        {
                            Id = 92,
                            Colors = "[\"blue\",\"black\"]",
                            Name = "Dismal Backwater",
                            TypeId = 10
                        },
                        new
                        {
                            Id = 93,
                            Colors = "[\"black\",\"red\"]",
                            Name = "Smoldering Marsh",
                            TypeId = 10
                        },
                        new
                        {
                            Id = 94,
                            Colors = "[\"red\",\"green\"]",
                            Name = "Cinder Barrens",
                            TypeId = 10
                        },
                        new
                        {
                            Id = 95,
                            Colors = "[\"green\",\"white\"]",
                            Name = "Tranquil Expanse",
                            TypeId = 10
                        },
                        new
                        {
                            Id = 96,
                            Colors = "[\"white\",\"black\"]",
                            Name = "Forsaken Sanctuary",
                            TypeId = 10
                        },
                        new
                        {
                            Id = 97,
                            Colors = "[\"blue\",\"red\"]",
                            Name = "Shivan Reef",
                            TypeId = 10
                        },
                        new
                        {
                            Id = 98,
                            Colors = "[\"black\",\"green\"]",
                            Name = "Jungle Hollow",
                            TypeId = 10
                        },
                        new
                        {
                            Id = 99,
                            Colors = "[\"red\",\"white\"]",
                            Name = "Clifftop Retreat",
                            TypeId = 10
                        },
                        new
                        {
                            Id = 100,
                            Colors = "[\"green\",\"blue\"]",
                            Name = "Yavimaya Coast",
                            TypeId = 10
                        },
                        new
                        {
                            Id = 101,
                            Colors = "[\"white\",\"blue\"]",
                            Name = "Mystic Gate",
                            TypeId = 11
                        },
                        new
                        {
                            Id = 102,
                            Colors = "[\"blue\",\"black\"]",
                            Name = "Cascade Bluffs",
                            TypeId = 11
                        },
                        new
                        {
                            Id = 103,
                            Colors = "[\"black\",\"red\"]",
                            Name = "Graven Cairns",
                            TypeId = 11
                        },
                        new
                        {
                            Id = 104,
                            Colors = "[\"blue\",\"red\"]",
                            Name = "Sunken Ruins",
                            TypeId = 11
                        },
                        new
                        {
                            Id = 105,
                            Colors = "[\"red\",\"green\"]",
                            Name = "Mystifying Maze",
                            TypeId = 11
                        },
                        new
                        {
                            Id = 106,
                            Colors = "[\"black\",\"green\"]",
                            Name = "Twilight Mire",
                            TypeId = 11
                        },
                        new
                        {
                            Id = 107,
                            Colors = "[\"white\",\"black\"]",
                            Name = "Sunken Ruins",
                            TypeId = 11
                        },
                        new
                        {
                            Id = 108,
                            Colors = "[\"white\",\"green\"]",
                            Name = "Twilight Mire",
                            TypeId = 11
                        },
                        new
                        {
                            Id = 109,
                            Colors = "[\"red\",\"white\"]",
                            Name = "Graven Cairns",
                            TypeId = 11
                        },
                        new
                        {
                            Id = 110,
                            Colors = "[\"blue\",\"green\"]",
                            Name = "Mystifying Maze",
                            TypeId = 11
                        },
                        new
                        {
                            Id = 111,
                            Colors = "[\"white\",\"blue\"]",
                            Name = "Temple of Enlightenment",
                            TypeId = 12
                        },
                        new
                        {
                            Id = 112,
                            Colors = "[\"black\",\"red\"]",
                            Name = "Temple of Malice",
                            TypeId = 12
                        },
                        new
                        {
                            Id = 113,
                            Colors = "[\"green\",\"blue\"]",
                            Name = "Temple of Mystery",
                            TypeId = 12
                        },
                        new
                        {
                            Id = 114,
                            Colors = "[\"red\",\"white\"]",
                            Name = "Temple of Abandon",
                            TypeId = 12
                        },
                        new
                        {
                            Id = 115,
                            Colors = "[\"white\",\"black\"]",
                            Name = "Temple of Silence",
                            TypeId = 12
                        },
                        new
                        {
                            Id = 116,
                            Colors = "[\"red\",\"white\"]",
                            Name = "Temple of Triumph",
                            TypeId = 12
                        },
                        new
                        {
                            Id = 117,
                            Colors = "[\"blue\",\"black\"]",
                            Name = "Temple of Deceit",
                            TypeId = 12
                        },
                        new
                        {
                            Id = 118,
                            Colors = "[\"green\",\"white\"]",
                            Name = "Temple of Plenty",
                            TypeId = 12
                        },
                        new
                        {
                            Id = 119,
                            Colors = "[\"blue\",\"red\"]",
                            Name = "Temple of Epiphany",
                            TypeId = 12
                        },
                        new
                        {
                            Id = 120,
                            Colors = "[\"black\",\"green\"]",
                            Name = "Temple of Malady",
                            TypeId = 12
                        },
                        new
                        {
                            Id = 121,
                            Colors = "[\"white\",\"blue\"]",
                            Name = "Tranquil Cove",
                            TypeId = 13
                        },
                        new
                        {
                            Id = 122,
                            Colors = "[\"white\",\"black\"]",
                            Name = "Forsaken Sanctuary",
                            TypeId = 13
                        },
                        new
                        {
                            Id = 123,
                            Colors = "[\"black\",\"red\"]",
                            Name = "Dragonskull Summit",
                            TypeId = 13
                        },
                        new
                        {
                            Id = 124,
                            Colors = "[\"red\",\"white\"]",
                            Name = "Clifftop Retreat",
                            TypeId = 13
                        },
                        new
                        {
                            Id = 125,
                            Colors = "[\"black\",\"green\"]",
                            Name = "Blooming Marsh",
                            TypeId = 13
                        },
                        new
                        {
                            Id = 126,
                            Colors = "[\"white\",\"black\"]",
                            Name = "Scoured Barrens",
                            TypeId = 13
                        },
                        new
                        {
                            Id = 127,
                            Colors = "[\"red\",\"white\"]",
                            Name = "Stone Quarry",
                            TypeId = 13
                        },
                        new
                        {
                            Id = 128,
                            Colors = "[\"black\",\"green\"]",
                            Name = "Jungle Hollow",
                            TypeId = 13
                        },
                        new
                        {
                            Id = 129,
                            Colors = "[\"white\",\"green\"]",
                            Name = "Sejiri Steppe",
                            TypeId = 13
                        },
                        new
                        {
                            Id = 130,
                            Colors = "[\"black\",\"white\"]",
                            Name = "Shambling Vent",
                            TypeId = 13
                        },
                        new
                        {
                            Id = 131,
                            Colors = "[\"white\",\"blue\"]",
                            Name = "Azorius Guildgate",
                            TypeId = 14
                        },
                        new
                        {
                            Id = 132,
                            Colors = "[\"blue\",\"black\"]",
                            Name = "Dimir Guildgate",
                            TypeId = 14
                        },
                        new
                        {
                            Id = 133,
                            Colors = "[\"black\",\"red\"]",
                            Name = "Rakdos Guildgate",
                            TypeId = 14
                        },
                        new
                        {
                            Id = 134,
                            Colors = "[\"red\",\"green\"]",
                            Name = "Gruul Guildgate",
                            TypeId = 14
                        },
                        new
                        {
                            Id = 135,
                            Colors = "[\"green\",\"white\"]",
                            Name = "Selesnya Guildgate",
                            TypeId = 14
                        },
                        new
                        {
                            Id = 136,
                            Colors = "[\"white\",\"black\"]",
                            Name = "Orzhov Guildgate",
                            TypeId = 14
                        },
                        new
                        {
                            Id = 137,
                            Colors = "[\"blue\",\"red\"]",
                            Name = "Izzet Guildgate",
                            TypeId = 14
                        },
                        new
                        {
                            Id = 138,
                            Colors = "[\"black\",\"green\"]",
                            Name = "Golgari Guildgate",
                            TypeId = 14
                        },
                        new
                        {
                            Id = 139,
                            Colors = "[\"red\",\"white\"]",
                            Name = "Boros Guildgate",
                            TypeId = 14
                        },
                        new
                        {
                            Id = 140,
                            Colors = "[\"green\",\"blue\"]",
                            Name = "Simic Guildgate",
                            TypeId = 14
                        });
                });

            modelBuilder.Entity("Domain.Models.LandType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LandTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "True Dual",
                            Priority = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fetchland",
                            Priority = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Shockland",
                            Priority = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bond Land",
                            Priority = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Triome",
                            Priority = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "Checkland",
                            Priority = 6
                        },
                        new
                        {
                            Id = 7,
                            Name = "Painland",
                            Priority = 7
                        },
                        new
                        {
                            Id = 8,
                            Name = "Fastland",
                            Priority = 8
                        },
                        new
                        {
                            Id = 9,
                            Name = "Pathway",
                            Priority = 9
                        },
                        new
                        {
                            Id = 10,
                            Name = "Slowland",
                            Priority = 10
                        },
                        new
                        {
                            Id = 11,
                            Name = "Filter Land",
                            Priority = 11
                        },
                        new
                        {
                            Id = 12,
                            Name = "Scryland",
                            Priority = 12
                        },
                        new
                        {
                            Id = 13,
                            Name = "Gainland",
                            Priority = 13
                        },
                        new
                        {
                            Id = 14,
                            Name = "Guildgate",
                            Priority = 14
                        });
                });

            modelBuilder.Entity("Domain.Models.DataModels.LandData", b =>
                {
                    b.HasOne("Domain.Models.LandType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });
#pragma warning restore 612, 618
        }
    }
}
